### ISSUE TITLE
Time sync solution for DVL-A50

### ISSUE THREAD

**Issue by CrazyPopLin** [waterlinked/docs#31]
Hi, is there any external trigger for the DVL? or any NTP based time sync solution while using Ethernet communication.

**Comment by wlest** [comment]
Hi,

As of now there is no support for external trigging of the DVL or other time sync solutions. The DVL reports the time between measurements. [https://waterlinked.github.io/dvl/dvl-protocol/#velocity-report_1](https://waterlinked.github.io/dvl/dvl-protocol/#velocity-report_1)
